### ISSUE TITLE
Parameter for salesinvoice.rptdesign does not work

### ISSUE THREAD

**Issue by lofidewanto** [interseroh/report-cockpit-birt-web#3]
The parameter "Order Naumber" should be shown directly if we call: 
http://localhost:8080/report-cockpit-birt-web/report/salesinvoice

just like the old Birt Viewer.

Choosing the parameter also does not work.

**Comment by lofidewanto** [comment]
The parameter should support following things for the first release:

1. String
2. Number
3. Date

Cascading parameter would be cool.

In general we should support the complete parameters from BIRT engine.

**Comment by idueppe** [comment]
A very simple parameter dialog is now working. The dialogs pops up if the report has any parameter. 
Numbers, String and Date should poorly work. But with a very simple type conversion. No localization etc. If no value is entered the default value of the parameter is taken if it exist.
- But still now speziell UI Component like Datepicker etc.
- Still no form validation or error handling. 

It is a starting point but the whole concept must be reworked. The REST-API for Rendering-Reports should work with a JSON-Object instead of Request-Parameters. This would enable us to deal with the possible hierarchical structure of cascading parameters and parameter groups. Also we must distinguish between simple and multi-value parameters.

**Comment by lofidewanto** [comment]
For Sales Invoice:
The "default" value of the parameter is missing... If I use the old BIRT Viewer you can see the default value...

**Comment by lofidewanto** [comment]
Date does not work.

If I define a Date value as a parameter I get an error for sending the params back to the server:

org.eclipse.birt.report.engine.api.impl.ParameterValidationException: The type of parameter "RP_Scandatum_Ende" is expected as "date", not "java.lang.String".
	org.eclipse.birt.report.engine.api.impl.EngineTask.validateParameterValueType(EngineTask.java:906)
	org.eclipse.birt.report.engine.api.impl.EngineTask.validateAbstractScalarParameter(EngineTask.java:862)
	org.eclipse.birt.report.engine.api.impl.EngineTask.access$0(EngineTask.java:789)
	org.eclipse.birt.report.engine.api.impl.EngineTask$ParameterValidationVisitor.visitScalarParameter(EngineTask.java:706)
	org.eclipse.birt.report.engine.api.impl.EngineTask$ParameterVisitor.visit(EngineTask.java:1531)
	org.eclipse.birt.report.engine.api.impl.EngineTask.doValidateParameters(EngineTask.java:692)
	org.eclipse.birt.report.engine.api.impl.RunAndRenderTask.doRun(RunAndRenderTask.java:95)
	org.eclipse.birt.report.engine.api.impl.RunAndRenderTask.run(RunAndRenderTask.java:77)
	de.interseroh.report.services.BirtReportServiceBean.runAndRenderTask(BirtReportServiceBean.java:244)

**Comment by idueppe** [comment]
I know these will be fixed with the ongoing refactoring of the parameter structure.

**Comment by idueppe** [comment]
With commit 89195e4 the foundation for converting and validation of report parameter is implemented. 

*Date*
But me must still configure a spring date converter to be able to convert parameters. At first, I would define a fix format for date like dd.mm.yyyy. Later we could extract the format information from the underlying report. 

*DefaultValue*
The defaultValue still doesn't work. I missed that the defaultValue is a string value instead of the concrete type of the report parameter. Therefore we need a conversion to the needed type.

**Comment by lofidewanto** [comment]
Date: still does not work, see screenshot: 

![error-date-birt](https://cloud.githubusercontent.com/assets/1212950/9261011/84f8f54e-420b-11e5-9262-59cc642a3ed4.png)

**Comment by lofidewanto** [comment]
MultipleValues: 
- I can choose all the items in the list box, example: Item1, Item2, Item3
- Problem: only the last item will be sent to the report engine, example: item3

**Comment by lofidewanto** [comment]
DefaultValue with JavaScript / BIRT function:
- It does not work.
- The function won't be interpreted, see screenshot:

![error-date-default-birt](https://cloud.githubusercontent.com/assets/1212950/9261419/0b46406e-420e-11e5-8999-7dbca5f519e7.png)

**Comment by lofidewanto** [comment]
Multiple Values:
I added an example for multiple values in this report: https://github.com/interseroh/report-cockpit-birt-web/blob/master/src/main/resources/reports/multiselect.rptdesign

I also added a JavaScript function which just logged out the chosen multi values items. In the log file you can see following difference:

1. Old BIRT Viewer:
strSelectedValues: 'Test1','Test2','Test3'
You have all three of the items if you choose them all.

2. Our BIRT cockpit:
strSelectedValues: 'Test3'
strResult Not Null: 'Test3'
You only have the last item although I choose all of them

**Comment by lofidewanto** [comment]
Multiple Values: works as expected now.
